resources:
  repositories:
    - repository: templates
      type: github
      name: dirigeants/pipelines
      endpoint: bdistin

trigger:
- master

jobs:
  - template: lint.yml@templates

  - template: scripts/.azure-test-template.yml
    parameters:
      name: Linux
      vmImage: 'ubuntu-16.04'

  - template: scripts/.azure-test-template.yml
    parameters:
      name: Mac
      vmImage: 'macOS-10.13'

  - template: scripts/.azure-test-template.yml
    parameters:
      name: Windows
      vmImage: 'vs2017-win2016'
