parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  dependsOn: Lint
  condition: succeeded()
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Node 10:
        nodeVersion: '10.x'
      Node 12:
        nodeVersion: '12.x'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js'
    - script: 'yarn'
      displayName: 'Install Dependencies'
    - script: 'yarn run test'
      displayName: 'Run Tests'
